### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by JorgeMaker** [byDeivid/Janus-Controller#2]
Hi, 

At your README file you have a bunch of broken links that result in 404 like this one: 

example code ->   https://github.com/byDagor/Janus-Controller/blob/master/JC01F05/JC01F05.ino

PS: Congratulations for your amazing project :)

**Comment by xpeedster** [comment]
Did you manage to get the link?

**Comment by JorgeMaker** [comment]
Hi @xpeedster 

No, but maybe this link is of your interest: https://github.com/byDagor/Janus-Controller/blob/master/JC20.01/JC01F022/JC01F022.ino

**Comment by jorenminer** [comment]
Yep, I can confirm @JorgeMaker 's comment is correct. In that same folder ('JC20.01') is also the file you originally requested. The one linked by JorgeMaker is the newer update.
